# Copyright (c) 2025 Shanghai Jiao Tong University.
# Contributed to the ModelEngine Community.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gpuDevicePlugin.name }}-configmap
  namespace: {{ .Values.basic.namespace }}
data:
  gpu-type.conf: |
    # Copyright (c) 2025 Shanghai Jiao Tong University.
    # Contributed to the ModelEngine Community.
    {{ range $key, $value := .Values.gpuTypeMap }}
    {{ $key }}: {{ $value }}
    {{ end }}