# Copyright (c) 2025 Shanghai Jiao Tong University.
# Contributed to the ModelEngine Community.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.devicePluginName }}-role
  namespace: {{ .Values.basic.namespace }}
  labels:
    name: {{ .Values.devicePluginName }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - update
      - patch