# Copyright (c) 2025 Shanghai Jiao Tong University.
# Contributed to the ModelEngine Community.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.devicePluginName }}-role-binding
  namespace: {{ .Values.basic.namespace }}
  labels:
    name: {{ .Values.devicePluginName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.devicePluginName }}-service-account
  namespace: {{ .Values.basic.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.devicePluginName }}-role
  apiGroup: rbac.authorization.k8s.io