# Copyright (c) 2025 Shanghai Jiao Tong University.
# Contributed to the ModelEngine Community.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.devicePluginName }}-service-account
  namespace: {{ .Values.basic.namespace }}
  labels:
    name: {{ .Values.devicePluginName }}