# Copyright (C) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-device-plugin
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - update
      - patch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-device-plugin
  namespace: xpu

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpu-device-plugin
subjects:
  - kind: ServiceAccount
    name: gpu-device-plugin
    namespace: xpu

---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-device-plugin-daemonset
  namespace: xpu
spec:
  selector:
    matchLabels:
      name: gpu-device-plugin
  updateStrategy:
    type: RollingUpdate
  template:
      metadata:
        labels:
          name: gpu-device-plugin
      spec:
        nodeSelector:
          huawei.com/vgpu: ready
        # Mark this pod as a critical add-on; when enabled, the critical add-on
        # scheduler reserves resources for critical add-on pods so that they can be scheduled after a failure.
        # See https://kubernetes.io/docs/tasks/administer-cluster/guraranteed-scheduling-critical-addon-pods/
        priorityClassName: "system-node-critical"
        runtimeClassName: nvidia
        hostPID: true
        hostNetwork: true
        containers:
          - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            image: gpu-device-plugin:v1.0.0
            args: ["--device-split-count=20", "--logging-console=true"]
            name: gpu-device-plugin
            volumeMounts:
              - name: device-plugin
                mountPath: /var/lib/kubelet/device-plugins
              - name: etc-xpu
                mountPath: /etc/xpu
              - name: cgroup
                mountPath: /sys/fs/cgroup
                readOnly: true
              - name: hostproc
                mountPath: /hostproc
                readOnly: true
              - name: xpu-log
                mountPath: /var/log/xpu
              - name: xpu-sock
                mountPath: /var/lib/xpu
        serviceAccountName: gpu-device-plugin
        volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: etc-xpu
          hostPath:
            type: DirectoryOrCreate
            path: /etc/xpu
        - name: cgroup
          hostPath:
            type: Directory
            path: /sys/fs/cgroup
        - name: hostproc
          hostPath:
            type: Directory
            path: /proc
        - name: xpu-log
          hostPath:
            type: DirectoryOrCreate
            path: /var/log/xpu
        - name: xpu-sock
          hostPath:
            path: /var/lib/xpu



