# Copyright (c) 2025 Shanghai Jiao Tong University.
# Contributed to the ModelEngine Community.

apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
  name: xpu