#ifndef CONST_VAR_H
#define CONST_VAR_H

#include "define.h"

#define IP_STRING_LEN          40
#define PORT_STRING_LEN        8

#define THREAD_NUM_PER_CLIENT  100
#define IOV_MAX_NUM            1000
#define PARAM_MAX_NUM          50
#define REG_PARAM_MAX_NUM      128 * 1024
#define TEST_STRING_LEN        50
#define REQUEST_BUFFER_SIZE    3LL * 1024 * 1024 * 1024
#define RECV_AM_SHIFT_BIT      8

#define BLOCK_ID_BIT                17
#define BLOCKS_MAX_NUM              (1LL << BLOCK_ID_BIT)                // 0.25M blocks
#define BLOCK_SHIFT_BIT             (64 - BLOCK_ID_BIT)                  // max size with 64TB for each block, nearly A100x800

#define HANDLE_MAX_NUM              800730
#define HANDLE_PREFIX               ((1LL << 54) | (1LL << 52) | (1LL << 50) | (1LL << 48)) // prefix: 0x55000000000000
#define HANDLE_MASK                 ((1LL << 48) - 1)      

#define BACKUP_STREAM_NUM           4
#define BACKUP_PERIOD               20
#define BACKUP_API_MAX_NUM          10000
#define COMM_EVENT_TIMEOUT          50

// static const char* BACKUP_FILE_DIR = "/mnt/nvme0/FlexGV_Test/Bak/";
static const char* BACKUP_FILE_DIR = "/mnt/nvme0/Bak163/";

static const size_t CONN_RESERVED_NUM = 1024;
static const uint32_t THREAD_STACK_SIZE = 8*1024*1024;

static const size_t DEVICE_POINTER_SIZE = sizeof(void *) * 2 + 3;
static const size_t HOST_POINTER_SIZE   = sizeof(void *) * 2 + 3;
static const size_t DEVICE_FUNC_INFO_SMALL_SIZE   = 1 * 1024 + 512 + 256; 
static const size_t DEVICE_FUNC_INFO_LARGE_SIZE   = 4 * 1024; 

enum SERVER_STATUS_SET {
    NORMAL_STATUS,
    // NODE_FAILURE, // cudaError or process failure
    EP_CLOSE,   // current endpoint ready to close (migration)
    COMM_ABORT  // communication abort
};

enum API_REQUEST_CODE_SET {
    /* CUDA Runtime API */
    SERVER_STATUS = 1,
    __CUDA_REGISTER = 2,
    __CUDA_REGISTER_FAT_BINARY, 
    __CUDA_REGISTER_FAT_BINARY_END, 
    __CUDA_UNREGISTER_FAT_BINARY,
    __CUDA_REGISTER_FUNCTION, 
    __CUDA_REGISTER_VAR, 
    CUDA_MALLOC, 
    CUDA_MEMCPY,
    CUDA_MEMCPY_H2D,
    CUDA_MEMCPY_D2H,
    CUDA_MEMCPY_D2D, 
    NEW_ITERATION_REQ, // used for identifying the new iteration
    CUDA_MEMCPY_ASYNC_H2D,
    CUDA_MEMCPY_ASYNC_D2H,
    CUDA_MEMCPY_ASYNC_D2D,
    CUDA_MEMCPY_TO_SYMBOL, 
    CUDA_MEM_GET_INFO, 
    CUDA_FREE, 
    CUDA_STREAM_CREATE,
    CUDA_STREAM_CREATE_WITH_FLAGS,
    CUDA_STREAM_CREATE_WITH_PRIORITY,
    CUDA_STREAM_DESTROY,
    CUDA_STREAM_WAIT_EVENT,
    CUDA_STREAM_SYNCHRONIZE,
    CUDA_STREAM_IS_CAPTURING,
    CUDA_STREAM_GET_CAPTURE_INFO,
    CUDA_EVENT_CREATE,
    CUDA_EVENT_CREATE_WITH_FLAGS,
    CUDA_EVENT_RECORD,
    CUDA_EVENT_QUERY,
    CUDA_EVENT_DESTROY,
    CUDA_EVENT_ELAPSED_TIME,
    CUDA_LAUNCH_KERNEL, 
    CUDA_FUNC_GET_ATTRIBUTES,
    CUDA_DEVICE_SYNCHRONIZE, 
    CUDA_MEMSET, 
    CUDA_MEMSET_ASYNC,
    CUDA_SET_DEVICE, 
    CUDA_SET_MAIN_DEVICE,
    CUDA_GET_DEVICE_COUNT, 
    CUDA_GET_DEVICE,
    CUDA_GET_DEVICE_PROPERTIES, 
    CUDA_DEVICE_GET_ATTRIBUTE,
    CUDA_OCCUPANCY_MAX_ACTIVE_BLOCKS_PER_MULTIPROCESSOR,
    CUDA_OCCUPANCY_MAX_ACTIVE_BLOCKS_PER_MULTIPROCESSOR_WITH_FLAGS,

    /* cuBlas API */
    CUBLAS_CREATE_V2,
    CUBLAS_SGEMM_V2,
    CUBLAS_SGEMM_STRIDED_BATCHED,
    CUBLAS_DESTROY_V2,
    CUBLAS_SET_STREAM_V2,
    CUBLAS_SET_WORKSPACE_V2,
    CUBLAS_SET_MATH_MODE,
    CUBLAS_GET_MATH_MODE,

    /* cuBlasLt API */
    CUBLASLT_CREATE,
    CUBLASLT_DESTROY,
    CUBLASLT_MATMULDESC_CREATE,
    CUBLASLT_MATMULDESC_DESTROY,
    CUBLASLT_MATMULDESC_SETATTRIBUTE,
    CUBLASLT_MATRIX_LAYOUT_CREATE,
    CUBLASLT_MATRIX_LAYOUT_DESTROY,
    CUBLASLT_MATRIX_LAYOUT_SETATTRIBUTE,
    CUBLASLT_MATMULPREFERENCE_CREATE,
    CUBLASLT_MATMULPREFERENCE_DESTROY,
    CUBLASLT_MATMULPREFERENCE_SETATTRIBUTE,
    CUBLASLT_MATMULALGO_GETHEURISTIC,
    CUBLASLT_MATMUL,

    /* cuDNN API */
    CUDNN_CREATE,
    CUDNN_DESTROY,
    CUDNN_CREATE_TENSOR_DESCRIPTOR,
    CUDNN_DESTROY_TENSOR_DESCRIPTOR,
    CUDNN_GET_TENSOR_SIZE_IN_BYTES,
    CUDNN_SET_TENSOR_4D_DESCRIPTOR,
    CUDNN_SET_TENSOR_ND_DESCRIPTOR,
    CUDNN_SET_TENSOR_ND_DESCRIPTOR_EX,
    CUDNN_CREATE_TENSOR_TRANSFORM_DESCRIPTOR,
    CUDNN_SET_TENSOR_TRANSFORM_DESCRIPTOR,
    CUDNN_DESTROY_TENSOR_TRANSFORM_DESCRIPTOR,
    CUDNN_INIT_TRANSFORM_DEST,
    CUDNN_TRANSFORM_TENSOR_EX,
    CUDNN_TRANSFORM_FILTER,
    CUDNN_CREATE_FILTER_DESCRIPTOR,
    CUDNN_SET_FILTER_ND_DESCRIPTOR,
    CUDNN_DESTROY_FILTER_DESCRIPTOR,
    CUDNN_GET_FILTER_SIZE_IN_BYTES,
    CUDNN_GET_FOLDED_CONV_BACKWARD_DATA_DESCRIPTORS,
    CUDNN_SET_STREAM,
    CUDNN_BATCH_NORMALIZATION_BACKWARD_EX,
    CUDNN_BATCH_NORMALIZATION_FORWARD_TRAINING_EX,
    CUDNN_BATCH_NORMALIZATION_FORWARD_INFERENCE,
    CUDNN_BACKEND_CREATE_DESCRIPTOR,
    CUDNN_BACKEND_DESTROY_DESCRIPTOR,
    CUDNN_BACKEND_SET_ATTRIBUTE,
    CUDNN_BACKEND_GET_ATTRIBUTE,
    CUDNN_BACKEND_EXECUTE,
    CUDNN_BACKEND_FINALIZE, 
    CUDNN_GET_BATCH_NORMALIZATION_BACKWARD_EX_WORKSPACE_SIZE,
    CUDNN_GET_BATCH_NORMALIZATION_FORWARD_TRAINING_EX_WORKSPACE_SIZE,
    CUDNN_GET_BATCH_NORMALIZATION_TRAINING_EX_RESERVE_SPACE_SIZE,
    CUDNN_CREATE_CONVOLUTION_DESCRIPTOR,
    CUDNN_DESTROY_CONVOLUTION_DESCRIPTOR,
    CUDNN_SET_CONVOLUTION_GROUP_COUNT,
    CUDNN_SET_CONVOLUTION_MATH_TYPE,
    CUDNN_SET_CONVOLUTION_ND_DESCRIPTOR,
    CUDNN_SET_CONVOLUTION_REORDER_TYPE,
    CUDNN_GET_CONVOLUTION_FORWARD_ALGORITHM_V7,
    CUDNN_GET_CONVOLUTION_BACKWARD_FILTER_ALGORITHM_V7,
    CUDNN_GET_CONVOLUTION_BACKWARD_DATA_ALGORITHM_V7,
    CUDNN_GET_CONVOLUTION_FORWARD_WORKSPACE_SIZE,
    CUDNN_CONVOLUTION_FORWARD,
    CUDNN_GET_CONVOLUTION_BACKWARD_DATA_WORKSPACE_SIZE,
    CUDNN_CONVOLUTION_BACKWARD_FILTER,
    CUDNN_GET_CONVOLUTION_BACKWARD_FILTER_WORKSPACE_SIZE,
    CUDNN_CONVOLUTION_BACKWARD_DATA,

    /* NCCL API */
    NCCL_GROUP_START,
    NCCL_GROUP_END,
    NCCL_COMM_INIT_RANK,
    NCCL_COMM_DESTROY,
    NCCL_COMM_GET_ASYNC_ERROR, 
    NCCL_GET_UNIQUE_ID,
    NCCL_GET_VERSION,
    NCCL_ALL_REDUCE,
    NCCL_REDUCE,
    NCCL_REDUCE_SCATTER,
    NCCL_ALL_GATHER,
    NCCL_BROADCAST,
    NCCL_SEND,
    NCCL_RECV,
    NCCL_COMM_COUNT, 
    NCCL_COMM_USER_RANK,
    NCCL_COMM_CU_DEVICE,
    NCCL_COMM_ABORT,
    NCCL_COMM_INIT_ALL, 
    NCCL_COMM_INIT_RANK_CONFIG, 
    NCCL_COMM_SPLIT,
    NCCL_COMM_FINALIZE,
    NCCL_COMM_REGISTER,
    NCCL_COMM_DEREGISTER,
    NCCL_MEM_ALLOC,
    NCCL_MEM_FREE,
    NCCL_RED_OP_CREATE_PRE_MUL_SUM,
    NCCL_RED_OP_DESTROY
};

enum MEMCPY_DATA_TYPE {
    MEMCPY_OTHER = 0,
    MEMCPY_TRAIN = 1,
    MEMCPY_VALID = 2,
    MEMCPY_MODEL = 3
};

const int NotNeedRecordAPIs[] = {
    /* CUDA Runtime API */
    // CUDA_MALLOC, // The validation phase of training sometimes needs to malloc memory
    // CUDA_MEMCPY_H2D,
    CUDA_MEMCPY_D2H,
    CUDA_MEMCPY_D2D,
    // CUDA_MEMCPY_ASYNC_H2D,
    CUDA_MEMCPY_ASYNC_D2H,
    // CUDA_MEMCPY_ASYNC_D2D,
    CUDA_MEMCPY_TO_SYMBOL,
    CUDA_MEM_GET_INFO,
    CUDA_FREE,
    CUDA_STREAM_IS_CAPTURING,
    CUDA_STREAM_GET_CAPTURE_INFO,
    CUDA_EVENT_ELAPSED_TIME, 
    CUDA_FUNC_GET_ATTRIBUTES,
    // CUDA_MEMSET,
    // CUDA_MEMSET_ASYNC,
    CUDA_SET_DEVICE,
    CUDA_SET_MAIN_DEVICE,
    CUDA_GET_DEVICE_COUNT,
    CUDA_GET_DEVICE,
    CUDA_GET_DEVICE_PROPERTIES,
    CUDA_DEVICE_GET_ATTRIBUTE,
    CUDA_OCCUPANCY_MAX_ACTIVE_BLOCKS_PER_MULTIPROCESSOR,
    CUDA_OCCUPANCY_MAX_ACTIVE_BLOCKS_PER_MULTIPROCESSOR_WITH_FLAGS,

    /* cuBlas API */
    CUBLAS_GET_MATH_MODE, 

    /* cuBlasLt API */
    CUBLASLT_MATMULALGO_GETHEURISTIC,

    /* cuDNN API */
    CUDNN_GET_TENSOR_SIZE_IN_BYTES,
    CUDNN_GET_FILTER_SIZE_IN_BYTES,
    //todo: backend APIs
    CUDNN_GET_BATCH_NORMALIZATION_BACKWARD_EX_WORKSPACE_SIZE,
    CUDNN_GET_BATCH_NORMALIZATION_FORWARD_TRAINING_EX_WORKSPACE_SIZE,
    CUDNN_GET_BATCH_NORMALIZATION_TRAINING_EX_RESERVE_SPACE_SIZE,
    CUDNN_GET_CONVOLUTION_FORWARD_ALGORITHM_V7,
    CUDNN_GET_CONVOLUTION_BACKWARD_FILTER_ALGORITHM_V7,
    CUDNN_GET_CONVOLUTION_BACKWARD_DATA_ALGORITHM_V7,
    CUDNN_GET_CONVOLUTION_FORWARD_WORKSPACE_SIZE,
    CUDNN_GET_CONVOLUTION_BACKWARD_DATA_WORKSPACE_SIZE,
    CUDNN_GET_CONVOLUTION_BACKWARD_FILTER_WORKSPACE_SIZE,

    /* NCCL API */
    // NCCL_GET_UNIQUE_ID,
    NCCL_GET_VERSION,
    NCCL_COMM_COUNT,
    NCCL_COMM_USER_RANK,
    NCCL_COMM_CU_DEVICE,
    NCCL_MEM_ALLOC,
    NCCL_MEM_FREE
};

const int ComputeAPIs[] = {
    /* CUDA Runtime API */
    NEW_ITERATION_REQ,
    CUDA_STREAM_WAIT_EVENT, // just a temporary state
    CUDA_STREAM_SYNCHRONIZE,
    CUDA_EVENT_RECORD, // just a temporary state
    CUDA_LAUNCH_KERNEL,
    CUDA_DEVICE_SYNCHRONIZE,

    /* cuBlas API */
    CUBLAS_SGEMM_V2,
    CUBLAS_SGEMM_STRIDED_BATCHED,

    /* cuBlasLt API */
    CUBLASLT_MATMUL,

    /* cuDNN API */
    CUDNN_BATCH_NORMALIZATION_BACKWARD_EX,
    CUDNN_BATCH_NORMALIZATION_FORWARD_TRAINING_EX,
    CUDNN_BATCH_NORMALIZATION_FORWARD_INFERENCE,
    //todo: backend APIs
    CUDNN_CONVOLUTION_FORWARD,
    CUDNN_CONVOLUTION_BACKWARD_FILTER,
    CUDNN_CONVOLUTION_BACKWARD_DATA,

    /* NCCL API */
    NCCL_GROUP_START,
    NCCL_GROUP_END,
    NCCL_COMM_GET_ASYNC_ERROR, 
    NCCL_ALL_REDUCE,
    NCCL_REDUCE,
    NCCL_REDUCE_SCATTER,
    NCCL_ALL_GATHER,
    NCCL_BROADCAST,
    NCCL_SEND,
    NCCL_RECV,
    // NCCL_COMM_FINALIZE
};

const int DestroyAPIs[] = {
    /* CUDA Runtime API */
    CUDA_STREAM_DESTROY,
    CUDA_EVENT_DESTROY,
    // CUDA_FREE,

    /* cuBlas API */
    CUBLAS_DESTROY_V2,

    /* cuBlasLt API */
    CUBLASLT_DESTROY,
    CUBLASLT_MATMULDESC_DESTROY,
    CUBLASLT_MATRIX_LAYOUT_DESTROY,
    CUBLASLT_MATMULPREFERENCE_DESTROY,


    /* cuDNN API */
    CUDNN_DESTROY,
    CUDNN_DESTROY_TENSOR_DESCRIPTOR,
    CUDNN_DESTROY_TENSOR_TRANSFORM_DESCRIPTOR,
    CUDNN_DESTROY_FILTER_DESCRIPTOR,
    // CUDNN_BACKEND_DESTROY_DESCRIPTOR,
    CUDNN_DESTROY_CONVOLUTION_DESCRIPTOR,

    /* NCCL API */
    NCCL_COMM_DESTROY,
    NCCL_COMM_DEREGISTER,
    // NCCL_MEM_FREE,
    NCCL_RED_OP_DESTROY
};

const int CreateAPIs[] = {
    /* CUDA Runtime API */
    CUDA_STREAM_CREATE,
    CUDA_STREAM_CREATE_WITH_FLAGS,
    CUDA_STREAM_CREATE_WITH_PRIORITY,
    CUDA_EVENT_CREATE,
    CUDA_EVENT_CREATE_WITH_FLAGS,   

    /* cuBlas API */
    CUBLAS_CREATE_V2,

    /* cuBlasLt API */
    CUBLASLT_CREATE,
    CUBLASLT_MATMULDESC_CREATE,
    CUBLASLT_MATRIX_LAYOUT_CREATE,
    CUBLASLT_MATMULPREFERENCE_CREATE,

    /* cuDNN API */
    CUDNN_CREATE,
    CUDNN_CREATE_TENSOR_DESCRIPTOR,
    CUDNN_CREATE_TENSOR_TRANSFORM_DESCRIPTOR,
    CUDNN_CREATE_FILTER_DESCRIPTOR,
    // CUDNN_BACKEND_CREATE_DESCRIPTOR,
    CUDNN_CREATE_CONVOLUTION_DESCRIPTOR,

    /* NCCL API */
    NCCL_COMM_INIT_RANK,
    NCCL_GET_UNIQUE_ID,
    NCCL_COMM_INIT_ALL,
    NCCL_COMM_INIT_RANK_CONFIG,
    NCCL_COMM_SPLIT, 
    NCCL_COMM_REGISTER,
    NCCL_RED_OP_CREATE_PRE_MUL_SUM 

};

#endif